name: Builds, tests & co

on:
  [pull_request, push]
permissions: read-all

jobs:
  build-and-test:
    name: Build and Test

    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
        ocaml-compiler:
          - 4.14.x
        include:
          - os: ubuntu-latest
            ocaml-compiler: ocaml-variants.4.14.0+options,ocaml-option-32bit
          - os: ubuntu-latest
            ocaml-compiler: ocaml-variants.4.14.0+options,ocaml-option-flambda,ocaml-option-musl,ocaml-option-static
          - os: ubuntu-latest
            ocaml-compiler: ocaml-variants.4.12.0+domains
            opam-repositories: |
              multicore: https://github.com/ocaml-multicore/multicore-opam.git
              default: https://github.com/ocaml/opam-repository.git
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install npm packages
        if: runner.os == 'Linux'
        run: yarn install --immutable

      - name: Check formatting
        if: runner.os == 'Linux'
        run: yarn fmt:check

      - name: Check lint
        if: runner.os == 'Linux'
        run: yarn lint

      - name: Check type
        if: runner.os == 'Linux'
        run: yarn typecheck
